In [1]:
from utils import list_r2_files, fetch_supabase_table

r2_files = list_r2_files()
supabase_data = fetch_supabase_table('websites_report_tracking')

In [4]:
supabase_data

,id,url,status,json_path,html_path,error_message,time_taken,updated_at
0,65e1a762-8c18-4468-8630-81119c15935b,https://www.kship.in,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:00:50.47,2024-10-20T23:39:07.499
1,b5c129de-7933-485c-b501-935cd519e644,https://sppanchmahal.gujarat.gov.in,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:01:40.77,2024-10-21T01:15:34.083
2,e6265bab-6848-4df4-9392-7b74a69be466,https://maharashtrasrpf.gov.in,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:01:32.43,2024-10-21T01:49:26.973
3,98ed850a-2cbe-406c-a1d9-eb823bb67113,https://chittoorpolice.ap.gov.in,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:00:39.28,2024-10-21T01:50:07.035
4,7d47bd98-5cbf-41e0-a30c-00025d2a001d,https://srfti.ac.in,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:01:35.65,2024-10-21T03:07:52.859
...,...,...,...,...,...,...,...,...
995,d4e0e394-31ad-4ce0-9c2e-8c8a023184c5,https://www.tn.gov.in/karuvoolam/whatsnew.html,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:02:29.25,2024-10-21T23:48:28.438
996,cec58042-7b4c-4f26-949b-c558d717a223,https://www.protean-tinpan.com,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:02:02.06,2024-10-21T23:50:31.421
997,9900c5b0-acc6-4521-bd7c-df6ceafd7056,https://meggst.gov.in,completed,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,https://govin-audit-reports.-Nx9v_SB994Ab4S-TC...,None,00:03:29.9,2024-10-21T23:50:30.571
998,3530085c-963c-4bfd-80a3-09ee41420ce0,https://epos.kerala.gov.in,pending,None,None,None,None,2024-10-22T02:11:34.207709
999,e84929fa-235a-4292-84ba-41b49ba5206e,https://aplm.gov.in,pending,None,None,None,None,2024-10-22T02:11:34.207709

In [2]:
r2_files.head()

,Key,Size,LastModified,path
0,govin-audit-reports/lighthouse-reports/html/00...,1138562,2024-10-21 03:38:24.602000+00:00,https://govin-audit-reports.r2.cloudflarestora...
1,govin-audit-reports/lighthouse-reports/html/00...,722113,2024-10-22 01:41:47.201000+00:00,https://govin-audit-reports.r2.cloudflarestora...
2,govin-audit-reports/lighthouse-reports/html/00...,617986,2024-10-22 00:32:14.256000+00:00,https://govin-audit-reports.r2.cloudflarestora...
3,govin-audit-reports/lighthouse-reports/html/00...,875630,2024-10-20 23:28:44.535000+00:00,https://govin-audit-reports.r2.cloudflarestora...
4,govin-audit-reports/lighthouse-reports/html/00...,902735,2024-10-22 00:13:49.175000+00:00,https://govin-audit-reports.r2.cloudflarestora...